kel11app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'kel11app'

urlpatterns = [
    path('', views.epay, name='epay'),
    path('success/', views.epaysuccess, name='epaysuccess'),
]

kel11project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kel11app.urls')),
    path('transfer/', include('transfer.urls')),

]

transfer/urls.py
from django.urls import path, include
from .views import transfer, status

urlpatterns = [
    path('form/', transfer, name='transfer'),
    path('status/', status, name='status')
]

kel11app/models.py
from django.db import models

# Create your models here.
class BayarListrik(models.Model):
    nama = models.CharField(max_length=30)
    token = models.CharField(max_length=9)
    tarif = models.CharField(max_length=9)

transfer/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Transfer(models.Model):
    nama = models.CharField(max_length=50)
    rekening = models.IntegerField()
    nominal = models.IntegerField()
    berita = models.CharField(max_length=100)
    waktu = models.DateTimeField(default=timezone.now)

kel11app/forms.py
from django import forms

class FormBayarListrik(forms.Form):
    attribute = {
        'class' : 'form-control'
    }

    nama = forms.CharField(max_length=30, label='Nama', required=True, widget=forms.TextInput(attrs=attribute))
    token = forms.CharField(max_length=9, label='Nomor Token', required=True, widget=forms.TextInput(attrs=attribute))
    tarif = forms.CharField(max_length=9, label='Tarif', required=True, widget=forms.TextInput(attrs=attribute))

transfer/forms.py
from django import forms
from .models import Transfer

class TransferForm(forms.Form):
    nama_form = forms.CharField(label='Nama Pengirim', max_length=50, 
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    rekening_form = forms.IntegerField(label='Nomor Rekening',
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    nominal_form = forms.IntegerField(label='Nominal',
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    berita_form = forms.CharField(label ='Berita', widget=forms.Textarea)

kel11app/views.py
from django.shortcuts import render,redirect
from .forms import FormBayarListrik
from .models import BayarListrik
from django.http import HttpResponse
from django.http import HttpResponseRedirect

response = {}
# Create your views here.
def epay(request):
    return render(request, 'epay.html', {'form': FormBayarListrik})

def epaycontents(request):
    contents = FormBayarListrik.objects.all().values()
    response['contents'] = convert_quaryset_into_json(contents)
    response['form'] = FormBayarListrik
    return render(request, 'epay.html', response)

def send(request):
    form = FormBayarListrik(request.POST)

    if request.method == 'POST':
        form = FormBayarListrik(request.POST)
        if form.is_valid():
            log = BayarListrik(nama = request.POST['nama'], token = request.POST['token'], tarif = request.POST['tarif'])
            log.save()
        return redirect("/success/")
    else:
        form = FormBayarListrik

def convert_quaryset_into_json(queryset):
    ret_val = []
    for data in queryset:
        ret_val.append(data)
    return ret_val

def epaysuccess(request):
    return render (request, 'epaysuccess.html')

transfer/views.py
from django.shortcuts import render, redirect   
from .models import Transfer
from .forms import TransferForm

# Create your views here.
def transfer(request):
    form_transfer = TransferForm(request.POST or None)
    if request.method == 'POST':
        if form_transfer.is_valid(): 
            Transfer.objects.create(
                nama = request.POST['nama_form'],
                rekening = request.POST['rekening_form'],
                nominal = request.POST['nominal_form'],
                berita = request.POST['berita_form']
            ) 
            return redirect('status')
    context = {
        'form': form_transfer
    }
    return render(request, 'transfer.html', context)

def status(request):
    obj = Transfer.objects.all().order_by("-waktu")
    context = {
        'data' : obj
    }
    return render(request, 'status.html', context)

kel11app/templates/epay.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>Top Up Token Listrik</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-light">
        <div class="container">
            <a class="navbar-brand">
                <img src="{% static 'img/logobank.png'%}" alt="nama bank" width="150" height="150"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link">Transfer</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'kel11app:epay' %}">Pembayaran<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container text-center">
        <div class="row">
            <div id="teks" class=" col-sm-10">
                <div style="margin-bottom: 4vh">
                <h1 class="text-center">Top Up Token Listrik</h1>
            </div>
                    <form action="/success/" method="POST">
                        {% csrf_token %}
                        <div class="form-group row" style="margin-bottom: 4vh">
                            <div class="col-sm-2 col-form-label">
                            {{form.nama.label}}
                        </div>
                            <div class="col-sm-10">
                                    {{form.nama}}
                            </div>
                        </div>
                        <div class="form-group row" style="margin-bottom: 4vh">
                                <div class="col-sm-2 col-form-label">
                                        {{form.tarif.label}}
                                    </div>
                                <div class="col-sm-10">
                                        {{form.tarif}}
                                </div>
                            </div>
                            <div class="form-group row" style="margin-bottom: 4vh">
                                    <div class="col-sm-2 col-form-label">
                                            {{form.token.label}}
                                        </div>
                                    <div class="col-sm-10">
                                            {{form.token}}
                                    </div>
                                </div>
                                <div class=" text-right">
                        <button class="btn btn-success" type="submit" style="background-color: #9999ff; border: #2A677C;" name="topup">Top Up</button>
                    </div>
                    </form>
                </div>

            </div>
        </div>
</body></html>

kel11app/templates/epayfailed.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>Top Up Token Listrik</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-light">
        <div class="container">
            <a class="navbar-brand">
                <img src="{% static 'img/logobank.png'%}" alt="nama bank" width="150" height="150"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link">Transfer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kel11app:epay' %}">Pembayaran</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div id="teks" class="col">
                <h1 class="text-center">Transaksi Gagal</h1>
                    <p class="text-center">
                        Pembayaran untuk Top Up Token Listrik gagal.
                        Mohon untuk mencobanya beberapa saat lagi.
                    </p>
            </div>
        </div>
    </div>

kel11app/templates/epaysuccess.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>Top Up Token Listrik</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top navbar-light">
        <div class="container">
            <a class="navbar-brand">
                <img src="{% static 'img/logobank.png'%}" alt="nama bank" width="150" height="150"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link">Transfer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'kel11app:epay' %}">Pembayaran</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div id="teks" class="col">
                <h1 class="text-center">Transaksi Berhasil</h1>
                    <p class="text-center">
                        Pembayaran untuk Top Up Token Listrik berhasil.
                    </p>
            </div>
        </div>
    </div>

transfer/templates/status.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>Riwayat Transfer</title>
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top navbar-light">
        <div class="container">
            <a class="navbar-brand">
                <img src="{% static 'img/logobank.png'%}" alt="nama bank" width="150" height="150"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'transfer:form' %}">Transfer</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'kel11app:epay' %}">Pembayaran<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
</nav>
<div class="row">
        <div class="col text-center">
          <h1>Riwayat Transfer</h1>
        </div>
</div>
<div>
{% for entry in data %}
<div class="card">
    <div class="col">
        <div class="row">
            <div class="col">
                <h4>Nama Pengirim: </h4>
            </div>
            <div class="col">
                <h4>{{entry.nama}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <h4>Nomor Rekening: </h4>
            </div>
            <div class="col">
                <h4>{{entry.rekening}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <h4>Nominal: </h4>
            </div>
            <div class="col">
                <h4>{{entry.nominal}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <h4>Berita: </h4>
            </div>
            <div class="col">
                <h4>{{entry.berita}}</h4>
            </div>
        </div>

        <div class="row">
            <div class="col">
                <h4>Waktu: </h4>
            </div>
            <div class="col">
                <h4>{{entry.waktu}}</h4>
            </div>
        </div>

    </div>
</div>
{% endfor %}
</div>
</body>
</html>

transfer/templates/transfer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    
    <title>Transfer</title>
</head>
<body>
<nav class="navbar navbar-expand-lg fixed-top navbar-light">
        <div class="container">
            <a class="navbar-brand">
                <img src="{% static 'img/logobank.png'%}" alt="nama bank" width="150" height="150"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'transfer:form' %}">Transfer</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'kel11app:epay' %}">Pembayaran<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </div>
</nav>
<div class="container">
    <div>
        <form method="POST">
            {% csrf_token %}

            <form>
                <div class="form-group row col-lg-10">
                    <label class="col-sm-2 col-form-label">{{form.nama_form.label}}</label>
                    <div class="col-sm-10">
                        {{form.nama_form}}
                    </div>
                </div>

                <div class="form-group row col-lg-10">
                    <label class="col-sm-2 col-form-label">{{form.rekening_form.label}}</label>
                    <div class="col-sm-10">
                        {{form.rekening_form}}
                    </div>
                </div>

                <div class="form-group row col-lg-10">
                    <label class="col-sm-2 col-form-label">{{form.nominal_form.label}} </label>
                    <div class="col-sm-10">
                        {{form.nominal_form}}
                    </div>
                </div>

                <div class="form-group row col-lg-10">
                    <label class="col-sm-2 col-form-label">{{form.berita_form.label}} </label>
                    <div class="col-sm-10">
                        {{form.berita_form}}
                    </div>
                </div>

                <button type="Submit" class="btn btn-primary">Transfer</button>
            </form>
        </form>
    </div>
</div>
</body>
</html>